"""Add cascade delete to mood_analysis.entry_id

Revision ID: 035ff65049d8
Revises: 461fd4be7b4c
Create Date: 2025-09-25 14:00:51.434237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '035ff65049d8'
down_revision: Union[str, Sequence[str], None] = '461fd4be7b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal_entries', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('journal_entries', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('mood_analysis', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('mood_analysis', 'entry_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('mood_analysis', 'sentiment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mood_analysis', 'emotion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mood_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('mood_analysis_entry_id_key'), 'mood_analysis', type_='unique')
    op.drop_constraint(op.f('fk_entry'), 'mood_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'mood_analysis', 'journal_entries', ['entry_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mood_analysis', 'recommendation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_analysis', sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mood_analysis', type_='foreignkey')
    op.create_foreign_key(op.f('fk_entry'), 'mood_analysis', 'journal_entries', ['entry_id'], ['id'])
    op.create_unique_constraint(op.f('mood_analysis_entry_id_key'), 'mood_analysis', ['entry_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('mood_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mood_analysis', 'emotion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mood_analysis', 'sentiment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mood_analysis', 'entry_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('mood_analysis', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('journal_entries', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('journal_entries', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
